# Generated by Django 3.1.7 on 2021-04-23 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_orders_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='Zipcode',
            new_name='zipcode',
        ),
    ]
