# Generated by Django 3.1.7 on 2021-04-23 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20210424_0001'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='zipcode',
            new_name='zip_code',
        ),
    ]
